// Interactive setup: prompts for API keys and stores them in .env (gitignored).
// Usage: npm run setup   (run by the user on their machine or server)
// This public repo NEVER contains real keys, only .env.example placeholders.
import { createInterface } from "node:readline";
import { writeFileSync, existsSync, readFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, "..");
const envPath = join(root, ".env");

const rl = createInterface({ input: process.stdin, output: process.stdout });

function ask(question, { hidden = false } = {}) {
  return new Promise((resolve) => {
    if (!hidden || !process.stdin.isTTY) {
      rl.question(question, (ans) => resolve(ans.trim()));
      return;
    }
    // Simple hidden input (does not echo typed chars).
    const stdin = process.stdin;
    let value = "";
    process.stdout.write(question);
    stdin.setRawMode(true);
    stdin.resume();
    const onData = (ch) => {
      const s = String(ch);
      if (s === "\n" || s === "\r" || s === "\u0004") {
        stdin.setRawMode(false);
        stdin.pause();
        stdin.removeListener("data", onData);
        process.stdout.write("\n");
        resolve(value.trim());
      } else if (s === "\u0003") {
        process.exit(1);
      } else if (s === "\u007f") {
        value = value.slice(0, -1);
      } else {
        value += s;
      }
    };
    stdin.on("data", onData);
  });
}

function mask(v) {
  if (!v) return "(vacía)";
  if (v.length <= 8) return "****";
  return v.slice(0, 4) + "…" + v.slice(-4) + ` (${v.length} chars)`;
}

const fields = [
  {
    key: "ZAI_API_KEY",
    label: "Z.ai API key (GLM Coding Plan: planner glm-5.3)",
    where: "Get it in your Z.ai dashboard -> API keys",
    required: true,
  },
  {
    key: "OPENCODE_GO_API_KEY",
    label: "OpenCode Go API key (cheap pool: flash / k2.7 / qwen-plus)",
    where: "Get it at opencode.ai -> Go -> API key",
    required: true,
  },
  {
    key: "OPENCODE_ZEN_API_KEY",
    label: "OpenCode Zen API key (pay-as-you-go buffer, optional)",
    where: "Get it at opencode.ai -> Zen. Enter to skip.",
    required: false,
  },
];

console.log("\n== Roleflow: interactive setup ==");
console.log("Stores keys in .env (gitignored). Nothing is uploaded to the repo.\n");

const current = {};
if (existsSync(envPath)) {
  for (const line of readFileSync(envPath, "utf8").split("\n")) {
    const m = line.match(/^([A-Z_]+)=(.*)$/);
    if (m) current[m[1]] = m[2];
  }
  console.log("A .env already exists, empty values are kept.\n");
}

const result = { ...current };
for (const f of fields) {
  console.log(`\n${f.label}`);
  console.log(`  ${f.where}`);
  if (current[f.key]) console.log(`  Current: ${mask(current[f.key])} (Enter to keep)`);
  const ans = await ask(`${f.key}: `, { hidden: true });
  if (ans) result[f.key] = ans;
  else if (!result[f.key] && f.required) {
    console.log("  ⚠ Left empty: the planner/pool using it will fail until you set it.");
    result[f.key] = "";
  }
}

const content =
  "# Generated by `npm run setup`. DO NOT commit (it is gitignored).\n" +
  Object.entries(result)
    .map(([k, v]) => `${k}=${v}`)
    .join("\n") +
  "\n";

writeFileSync(envPath, content);
console.log(`\n✔ Saved to ${envPath}`);
console.log("The plugin auto-loads it (project root or ~/.config/opencode/.env).");
console.log("Open OpenCode in your project and the plugin picks the keys up.\n");
rl.close();
